/*

> SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS where table_name in ('ARTIST', 'ALBUM')
> SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE


> SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS where constraint_type = 'FOREIGN KEY'

PUBLIC	PUBLIC	FK5897E6FCECEA062	FOREIGN KEY	PUBLIC	PUBLIC	ALBUM	NO	NO
PUBLIC	PUBLIC	FK5897E6F410589A2	FOREIGN KEY	PUBLIC	PUBLIC	ALBUM	NO	NO
PUBLIC	PUBLIC	FK697F14BF699F5D2	FOREIGN KEY	PUBLIC	PUBLIC	TRACK	NO	NO
PUBLIC	PUBLIC	FK697F14BE500BE52	FOREIGN KEY	PUBLIC	PUBLIC	TRACK	NO	NO

> SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE CONSTRAINT_NAME like 'FK5897E6FCECEA062'

PUBLIC	PUBLIC	ALBUM	ARTIST_ID	PUBLIC	PUBLIC	FK5897E6FCECEA062

> SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE CONSTRAINT_NAME like 'FK5897E6F410589A2'

PUBLIC	PUBLIC	ALBUM	MEDIUM_ID	PUBLIC	PUBLIC	FK5897E6F410589A2

> SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE CONSTRAINT_NAME like 'FK697F14BF699F5D2'

PUBLIC	PUBLIC	TRACK	GENRE_ID	PUBLIC	PUBLIC	FK697F14BF699F5D2

> SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE CONSTRAINT_NAME like 'FK697F14BE500BE52'

PUBLIC	PUBLIC	TRACK	ALBUM_ID	PUBLIC	PUBLIC	FK697F14BE500BE52


*/